language: python

env: 
  global: 
    - SWMM_HOME=`pwd`
    - BUILD_HOME=build
    - TEST_HOME=tests/swmm-nrtestsuite

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig 

install:
  - pip install -r tools/requirements.txt

before_script:
  - mkdir -p $BUILD_HOME
  - cd $BUILD_HOME
  - cmake ..

script:
  - make
  - cd $SWMM_HOME
  - tools/gen-config.sh $SWMM_HOME/$BUILD_HOME/bin > $TEST_HOME/apps/swmm-$TRAVIS_COMMIT.json
  - tools/run-nrtest.sh $TEST_HOME $TRAVIS_COMMIT
