# https://ci.appveyor.com/project/OpenWaterAnalytics/stormwater-management-model/

version: 2.0.{build}

platform:
  - x64

matrix:
  allow_failures:
    #Group: (EXPERIMENTAL / SUPPORTED)
    #EXPERIMENTAL is allowed to fail under the build matrix
    - GROUP: "EXPERIMENTAL"

environment:
  BENCH_COMMIT: ""
  matrix:
    # Python 3.4
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      GROUP: "SUPPORTED"
      BOOST_ROOT: "C:/Libraries/boost_1_67_0"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
      GROUP: "EXPERIMENTAL"
      BOOST_ROOT: "C:/Libraries/boost_1_67_0"

init:
  - set SWMM_HOME=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_HOME=buildprod
  - set TEST_HOME=nrtestsuite
  # See set values
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - echo %BUILD_HOME%
  - echo %GENERATOR%
  - echo %BOOST_ROOT%

install:
  # Install nrtest and dependencies for regression tests
  - python -m pip install -r tools\requirements-appveyor.txt

before_build:
  - mkdir %BUILD_HOME%
  - cd %BUILD_HOME%
  - cmake -G "%GENERATOR%"
    -DBUILD_TESTS=1
    -DBOOST_ROOT="%BOOST_ROOT%"
    -DBoost_USE_STATIC_LIBS="ON" ..

build_script:
  - cmake --build . --config Release

before_test:
  - cd %SWMM_HOME%
  - tools\before-test.cmd %APPVEYOR_REPO_COMMIT%
  - echo %BENCH_COMMIT%
  
test_script:
  # run unit tests
  - cd %BUILD_HOME%\tests
  - ctest -C Release
    # Run regression tests
  - cd %SWMM_HOME%
  - tools\run-nrtest.cmd %APPVEYOR_REPO_COMMIT%

on_finish:
  - cd %TEST_HOME%\benchmark
  # zip up the SUT benchmarks
  - 7z a swmm-benchmark.zip .\swmm-%APPVEYOR_REPO_COMMIT%
  - appveyor PushArtifact swmm-benchmark.zip -FileName swmm-benchmark.zip

#cache:
#  - C:\ProgramData\chocolatey\bin -> appveyor.yml
#  - C:\ProgramData\chocolatey\lib -> appveyor.yml
