# https://ci.appveyor.com/project/OpenWaterAnalytics/stormwater-management-model/

version: 2.0.{build}

configuration:
  - Release

platform:
  - x64

environment:
  matrix:
#    # Python 2.7
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      VS_VERSION: "9 2008"
#      arch: Win32
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      VS_VERSION: "9 2008"
#      arch: Win64
    # Python 3.4
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: "10 2010"
      arch: Win32
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      VS_VERSION: "10 2010"
#      arch: Win64
#    # Not used as a python compiler
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      VS_VERSION: "12 2013"
#      arch: Win32
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      VS_VERSION: "12 2013"
#      arch: Win64
#    # Python 3.5 and 3.6
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      VS_VERSION: "14 2015"
#      arch: Win32
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      VS_VERSION: "14 2015"
#      arch: Win64
#    # Not used as a python compiler
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      VS_VERSION: "15 2017"
#      arch: Win32
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      VS_VERSION: "15 2017"
#      arch: Win64
  
matrix:
  fast_finish: false

# skip unsupported combinations
init:
  - set _arch=
  - if "%arch%"=="Win64" ( set _arch= Win64)
  - echo %_arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - set generator="Visual Studio %VS_VERSION%%_arch%" 
  - echo %generator%

before_build:
- cmd: >-
    cmake -G %generator% -DCMAKE_INSTALL_PREFIX:PATH=output -DCMAKE_BUILD_TYPE:STRING=Release


build_script:
  - MSBUILD.exe INSTALL.vcxproj /p:Configuration=Release

after_test:
  - cd output/bin
  - run-swmm.exe --version
