#
#  build-and-test.yml - GitHub Actions CI for swmm-solver
#
#  Created: May 19, 2020
#  Updated: Aug 13, 2020
#
#  Author: Michael E. Tryby
#          US EPA - ORD/CESER
#
#          Caleb A. Buahin
#          Xylem Inc.
#

name: Build and Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    defaults:
      run:
        working-directory: ${{ matrix.defaults.run.working-directory}}
    env:
      OMP_NUM_THREADS: 1
      PROJECT: swmm
      BUILD_HOME: build
      TEST_HOME: nrtests 
      NRTESTS_URL: https://github.com/OpenWaterAnalytics/swmm-nrtestsuite
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, ubuntu-latest, macos-latest]
        requirements: [requirements-swmm.txt]
        include:
          - os: windows-2016
            generator: Visual Studio 15 2017 Win64
            experimental: true
            script_extension: cmd
            defaults:
              run:
                shell: cmd
                working-directory: ./ci-tools/windows

          - os: ubuntu-latest
            generator: "Unix Makefiles" 
            experimental: true
            script_extension: sh
            defaults:
              run:
                shell: bash
                working-directory: ./ci-tools/linux

          - os: macos-latest
            generator: Xcode
            experimental: true
            ci_tools_path: ci-tools/darwin
            script_extension: zsh
            defaults:
              run:
                shell: zsh
                working-directory: ./ci-tools/darwin

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          repository: OpenWaterAnalytics/ci-tools
          path: ci-tools

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ${{ matrix.requirements }}

      - name: Build and unit test
        run: |
          make.${{ matrix.script_extension }} -t -g "${{ matrix.generator }}"

      - name: Build for reg test
        run: |
          make.${{ matrix.script_extension }} -g "${{ matrix.generator }}"
 
      - name: Before reg test
        run: |
          before-nrtest.${{ matrix.script_extension }}

      - name: Run reg test
        run: |
          run-nrtests.${{ matrix.script_extension }} %GITHUB_RUN_ID%_%GITHUB_RUN_NUMBER%

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-test-artifacts
          path: upload/*.*

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload release ssset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: upload/*.zip
          asset_content_type: application/zip